# Generated by Django 3.1.5 on 2021-05-24 15:47

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poiapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pointofinterest',
            name='longitude',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
    ]
